# Generated by Django 4.0.2 on 2022-02-22 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Ответы',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя параметра')),
                ('name_for_formula', models.CharField(max_length=200, verbose_name='Имя для формулы')),
                ('field_type', models.CharField(choices=[('int', 'Число'), ('bool', 'Выбор'), ('choice', 'Шкала')], max_length=10)),
            ],
            options={
                'verbose_name': 'Параметры',
                'verbose_name_plural': 'Параметры',
            },
        ),
        migrations.CreateModel(
            name='ParameterTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.parameter', verbose_name='Параметер')),
            ],
            options={
                'verbose_name': 'Параметр - Тест',
                'verbose_name_plural': 'Параметр - Тест',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название теста')),
                ('description', models.TextField(default='<django.db.models.fields.CharField>', verbose_name='Описание теста')),
                ('formula', models.CharField(max_length=400, verbose_name='Формула')),
                ('achievements', models.ManyToManyField(through='tests.ParameterTest', to='tests.Parameter', verbose_name='Все параметры')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='tests.answer', verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Тесты',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.AddField(
            model_name='parametertest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='answer',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.test', verbose_name='Тест'),
        ),
        migrations.AddConstraint(
            model_name='parametertest',
            constraint=models.UniqueConstraint(fields=('test', 'parameter'), name='unique_parameter'),
        ),
    ]
