# Generated by Django 4.0.2 on 2022-02-19 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя параметра'),
        ),
        migrations.AlterField(
            model_name='parametertest',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.parameter', verbose_name='Параметер'),
        ),
        migrations.AlterField(
            model_name='parametertest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='test',
            name='achievements',
            field=models.ManyToManyField(through='tests.ParameterTest', to='tests.Parameter', verbose_name='Все параметры'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название теста'),
        ),
    ]
