# Generated by Django 4.0.2 on 2022-02-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(verbose_name='Описание теста'),
        ),
    ]
