# Generated by Django 4.0.2 on 2022-05-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя параметра'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя параметра'),
        ),
        migrations.AddField(
            model_name='test',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание теста'),
        ),
        migrations.AddField(
            model_name='test',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание теста'),
        ),
        migrations.AddField(
            model_name='test',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название теста'),
        ),
        migrations.AddField(
            model_name='test',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название теста'),
        ),
    ]
