# Generated by Django 4.0.2 on 2022-02-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.ImageField(blank=True, upload_to='tests/', verbose_name='Картинка'),
        ),
    ]
