# Generated by Django 4.0.2 on 2022-02-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_parameter_name_alter_parametertest_parameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(default='Hi', verbose_name='Описание теста'),
        ),
    ]
