# Generated by Django 4.0.2 on 2022-02-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_test_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(default='f{title}', verbose_name='Описание теста'),
        ),
    ]
