# Generated by Django 4.0.2 on 2022-02-22 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_test_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='tests.answer', verbose_name='Ответ'),
        ),
    ]
