# Generated by Django 4.0.2 on 2022-02-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_test_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(default='<django.db.models.fields.CharField>', verbose_name='Описание теста'),
        ),
    ]
