# Generated by Django 4.0.2 on 2022-02-22 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_alter_test_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='tests.answer', verbose_name='Ответы'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('test', 'answer'), name='unique_answer'),
        ),
    ]
