# Generated by Django 4.0.2 on 2022-02-22 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_alter_test_answer_answer_unique_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Ответ - Тест',
                'verbose_name_plural': 'Ответ - Тест',
            },
        ),
        migrations.RemoveConstraint(
            model_name='parametertest',
            name='unique_parameter',
        ),
        migrations.RemoveField(
            model_name='test',
            name='answer',
        ),
        migrations.AddField(
            model_name='test',
            name='answers',
            field=models.ManyToManyField(related_name='choice_answer', through='tests.AnswerTest', to='tests.Answer', verbose_name='Все ответы'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_test', to='tests.test', verbose_name='Тест'),
        ),
        migrations.AddConstraint(
            model_name='parameter',
            constraint=models.UniqueConstraint(fields=('name', 'name_for_formula', 'field_type'), name='unique_parameter'),
        ),
        migrations.AddConstraint(
            model_name='parametertest',
            constraint=models.UniqueConstraint(fields=('test', 'parameter'), name='unique_parameter_test'),
        ),
        migrations.AddField(
            model_name='answertest',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.answer', verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='answertest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Тест'),
        ),
        migrations.AddConstraint(
            model_name='answertest',
            constraint=models.UniqueConstraint(fields=('test', 'answer'), name='unique_answer_test'),
        ),
    ]
