# Generated by Django 4.0.2 on 2022-02-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_answertest_remove_parametertest_unique_parameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
